### ISSUE TITLE
[TASK] come say hi?

### ISSUE THREAD

**Issue by jntrnr** [kdr-aus/ogma#11]
## Goal

Hi - I'm JT and I work on the Nushell project. We just found out about this project, very cool! Are interested in coming to say "hi" on the [Nushell discord](https://discord.gg/NtAbbGn), by chance? We've got a channel called `#external-collab` where folks interested in this area can collaborate with each other, brainstorm ideas, etc.

**Comment by kurtlawrence** [comment]
Will do JT!
