### ISSUE TITLE
[TASK] Alter `Expecting` enum to be a bitflag

### ISSUE THREAD

**Issue by kurtlawrence** [kdr-aus/ogma#168]
## Goal

Alter the `Expecting` enum from parsing to use bitflags, indicating it could be composed of more than a single variant.

https://github.com/kdr-aus/ogma/blob/a1952df8534562c486145e6ee1400ad5a213a6f3/ogma/src/lang/syntax/parse.rs#L112

**Comment by yuchunzhou** [comment]
@kurtlawrence hi kurtlawrence, maybe i can refactor it with [https://crates.io/crates/bitflags](bitflags)

**Comment by kurtlawrence** [comment]
@yuchunzhou yep, that is what I was thinking. You are welcome to raise a PR =)

**Comment by yuchunzhou** [comment]
@kurtlawrence hi kurt, i have raised the PR(#169), please review it.

**Comment by kurtlawrence** [comment]
Closed with #169
